name: coo-secrets-rotation-check
on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:
jobs:
  run:
    uses: ./.github/workflows/_runner.yml
    with:
      routine_id: secrets-rotation-check
      tier: A
    secrets: inherit
